"""init

Revision ID: 14840a2167d7
Revises: 
Create Date: 2026-03-18 00:07:18.539697

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '14840a2167d7'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('projects',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('short_description', sa.Text(), nullable=False),
    sa.Column('full_description', sa.Text(), nullable=False),
    sa.Column('tags', sa.Text(), nullable=False),
    sa.Column('github_url', sa.String(length=500), nullable=False),
    sa.Column('live_url', sa.String(length=500), nullable=False),
    sa.Column('cover_image', sa.String(length=500), nullable=False),
    sa.Column('is_featured', sa.Boolean(), nullable=False),
    sa.Column('is_published', sa.Boolean(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_projects_created_at'), 'projects', ['created_at'], unique=False)
    op.create_index(op.f('ix_projects_is_featured'), 'projects', ['is_featured'], unique=False)
    op.create_index(op.f('ix_projects_is_published'), 'projects', ['is_published'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_projects_is_published'), table_name='projects')
    op.drop_index(op.f('ix_projects_is_featured'), table_name='projects')
    op.drop_index(op.f('ix_projects_created_at'), table_name='projects')
    op.drop_table('projects')
    # ### end Alembic commands ###
